Place: Место
Contestant: Участник
LastSuccessTime: Время
CorrectSolutions: Правильных решений:
AdditionalInformation: Наведите курсор на ячейку, чтобы получить дополнительную информацию о задаче/участнике/посылке.
PageGenerationTime link@Text version@Text: Эта страница была сгенерирована <a href="#{link}">EjStand</a> #{version} за %%GENERATION_TIME%% мс.
EjStandLicense: Это свободная программа, вы можете распространять и/или изменять ее на условиях лицензии <a href="https://www.gnu.org/licenses/agpl-3.0.ru.html">GNU Affero General Public License</a> версии 3.
OtherLicenses link@Text: В состав данного ПО также входят свободные библиотки под <a href="#{link}">другими лицензиями</a>.
ThirdPartyLicensesCaption: Лицензии вспомогательных библиотек
ThirdPartyLicensesDescription: В данном разделе представлена информация о лицензиях вспомогательных библиотек, использованных при создании EjStand. Более подробную информацию можно найти по ссылкам в Hackage.